<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Wert löschen',
    'Close the picker' => 'Kalender schließen',
    'Decrement Hour' => 'Stunden verringern',
    'Decrement Minute' => 'Verkürzen Sie die Minuten',
    'Decrement Second' => 'Verringern Sie die Sekunden',
    'Go to today' => 'Gehe zum heutigen Datum',
    'Increment Hour' => 'Erhöhen Sie die Stunde',
    'Increment Minute' => 'Minuten erhöhen',
    'Increment Second' => 'Sekunden erhöhen',
    'Next Century' => 'Das nächste Jahrhundert',
    'Next Decade' => 'Das nächste Jahrzehnt',
    'Next Month' => 'Nächsten Monat',
    'Next Year' => 'Nächstes Jahr',
    'Pick Hour' => 'Wählen Sie eine Stunde',
    'Pick Minute' => 'Wählen Sie Minuten',
    'Pick Second' => 'Wählen Sie Sekunden',
    'Previous Century' => 'Das vorherige Jahrhundert',
    'Previous Decade' => 'Vorheriges Jahrzehnt',
    'Previous Month' => 'Vorheriger Monat',
    'Previous Year' => 'Vorheriges Jahr',
    'Select Decade' => 'Wähle ein Jahrzehnt',
    'Select Month' => 'Wählen Sie den Monat aus',
    'Select Time' => 'Stellen Sie die Uhrzeit ein',
    'Select Year' => 'Wählen Sie Jahr',
    'Toggle Period' => 'Wechselintervall',
];

















